// <auto-generated />
namespace Gestion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class GenericLogDescriptioj : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GenericLogDescriptioj));
        
        string IMigrationMetadata.Id
        {
            get { return "201609152051381_GenericLogDescriptioj"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
