// <auto-generated />
namespace Paramedic.Gestion.Web
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MailRequiredInUserProfileEmails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MailRequiredInUserProfileEmails));
        
        string IMigrationMetadata.Id
        {
            get { return "201704121815138_MailRequiredInUserProfileEmails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
