// <auto-generated />
namespace Paramedic.Gestion.Web
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TicketClasificacionUsuarios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TicketClasificacionUsuarios));
        
        string IMigrationMetadata.Id
        {
            get { return "201704031910037_TicketClasificacionUsuarios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
